// <auto-generated />
using System;
using ClickNEat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickNEat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505211533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickNEat.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            Description = "Boeuf grillé, laitue, tomate, cheddar",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Burger Classic",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burgers",
                            Description = "Boeuf grillé, bacon, oignon caramélisé, sauce BBQ",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Burger BBQ",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, basilic frais",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Pizza Margherita",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, pepperoni",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Pizza Pepperoni",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Salades",
                            Description = "Romaine, croûtons, parmesan, sauce césar",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Salade César",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Accompagnements",
                            Description = "Frites maison croustillantes",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Boissons",
                            Description = "355 ml",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Boissons",
                            Description = "500 ml",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Eau",
                            Price = 1.99m
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ClickNEat.Core.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
