// <auto-generated />
using System;
using ClickNEat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickNEat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505211955_SeedMoreData")]
    partial class SeedMoreData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickNEat.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            Description = "Boeuf grillé, laitue, tomate, cheddar",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Burger Classic",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burgers",
                            Description = "Boeuf grillé, bacon, oignon caramélisé, sauce BBQ",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Burger BBQ",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Burgers",
                            Description = "Galette de pois chiches, avocat, tomate, mayo citron",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Burger Végé",
                            Price = 13.49m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Burgers",
                            Description = "Double boeuf, double cheddar, bacon, sauce maison",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Burger Double",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, basilic frais",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Pizza Margherita",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, pepperoni",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Pizza Pepperoni",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Pizzas",
                            Description = "Mozzarella, gorgonzola, parmesan, chèvre",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Pizza 4 Fromages",
                            Price = 16.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Pizzas",
                            Description = "Sauce BBQ, poulet grillé, oignon rouge, mozzarella",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Pizza BBQ Poulet",
                            Price = 16.49m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Salades",
                            Description = "Romaine, croûtons, parmesan, sauce césar",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Salade César",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Salades",
                            Description = "Tomate, concombre, feta, olives, oignon rouge",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Salade Grecque",
                            Price = 10.49m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Salades",
                            Description = "Poulet grillé, mesclun, avocat, vinaigrette miel-moutarde",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Salade Poulet Grillé",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accompagnements",
                            Description = "Frites maison croustillantes",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accompagnements",
                            Description = "Frites, fromage en grains, sauce brune",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accompagnements",
                            Description = "Rondelles d'oignon panées, sauce ranch",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Rondelles d'oignon",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accompagnements",
                            Description = "Soupe maison avec pain grillé",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Soupe du jour",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Desserts",
                            Description = "Moelleux au chocolat, coulis de caramel",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Gâteau au chocolat",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Desserts",
                            Description = "Crème brûlée à la vanille",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Crème brûlée",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Desserts",
                            Description = "Tiramisu classique au café et mascarpone",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Boissons",
                            Description = "355 ml",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Boissons",
                            Description = "500 ml",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Eau",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Boissons",
                            Description = "Jus d'orange pressé, 300 ml",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Jus d'orange",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Boissons",
                            Description = "Citron frais, menthe, eau gazeuse",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Limonade maison",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Boissons",
                            Description = "Espresso, allongé ou cappuccino",
                            ImageUrl = "",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 2.49m
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ClickNEat.Core.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
