// <auto-generated />
using System;
using ClickNEat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickNEat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506051730_FixImageUrls")]
    partial class FixImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickNEat.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            Description = "Boeuf grillé, laitue, tomate, cheddar",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger Classic",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burgers",
                            Description = "Boeuf grillé, bacon, oignon caramélisé, sauce BBQ",
                            ImageUrl = "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger BBQ",
                            Price = 14.99m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Burgers",
                            Description = "Galette de pois chiches, avocat, tomate, mayo citron",
                            ImageUrl = "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger Végé",
                            Price = 13.49m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Burgers",
                            Description = "Double boeuf, double cheddar, bacon, sauce maison",
                            ImageUrl = "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger Double",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, basilic frais",
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza Margherita",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, pepperoni",
                            ImageUrl = "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza Pepperoni",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Pizzas",
                            Description = "Mozzarella, gorgonzola, parmesan, chèvre",
                            ImageUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza 4 Fromages",
                            Price = 16.99m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Pizzas",
                            Description = "Sauce BBQ, poulet grillé, oignon rouge, mozzarella",
                            ImageUrl = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza BBQ Poulet",
                            Price = 16.49m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Salades",
                            Description = "Romaine, croûtons, parmesan, sauce césar",
                            ImageUrl = "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Salade César",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Salades",
                            Description = "Tomate, concombre, feta, olives, oignon rouge",
                            ImageUrl = "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Salade Grecque",
                            Price = 10.49m
                        },
                        new
                        {
                            Id = 11,
                            Category = "Salades",
                            Description = "Poulet grillé, mesclun, avocat, vinaigrette miel-moutarde",
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Salade Poulet Grillé",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accompagnements",
                            Description = "Frites maison croustillantes",
                            ImageUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 4.99m
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accompagnements",
                            Description = "Frites, fromage en grains, sauce brune",
                            ImageUrl = "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accompagnements",
                            Description = "Rondelles d'oignon panées, sauce ranch",
                            ImageUrl = "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Rondelles d'oignon",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accompagnements",
                            Description = "Soupe maison avec pain grillé",
                            ImageUrl = "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Soupe du jour",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 16,
                            Category = "Desserts",
                            Description = "Moelleux au chocolat, coulis de caramel",
                            ImageUrl = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Gâteau au chocolat",
                            Price = 6.99m
                        },
                        new
                        {
                            Id = 17,
                            Category = "Desserts",
                            Description = "Crème brûlée à la vanille",
                            ImageUrl = "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Crème brûlée",
                            Price = 5.99m
                        },
                        new
                        {
                            Id = 18,
                            Category = "Desserts",
                            Description = "Tiramisu classique au café et mascarpone",
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 6.49m
                        },
                        new
                        {
                            Id = 19,
                            Category = "Boissons",
                            Description = "355 ml",
                            ImageUrl = "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.99m
                        },
                        new
                        {
                            Id = 20,
                            Category = "Boissons",
                            Description = "500 ml",
                            ImageUrl = "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Eau",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 21,
                            Category = "Boissons",
                            Description = "Jus d'orange pressé, 300 ml",
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Jus d'orange",
                            Price = 3.49m
                        },
                        new
                        {
                            Id = 22,
                            Category = "Boissons",
                            Description = "Citron frais, menthe, eau gazeuse",
                            ImageUrl = "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Limonade maison",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 23,
                            Category = "Boissons",
                            Description = "Espresso, allongé ou cappuccino",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 2.49m
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@clickneat.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$X8aEcMTN7Ag/5iqJgyr1N.lrQ4D8X67/kevqA6B5qUxo3BDQpbHKy",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "client@clickneat.com",
                            Name = "Client Test",
                            PasswordHash = "$2a$11$uumzhUwh0rpbuNR/XzSrC.i6rWaHiyhSNEgVAcgTMlGpnfF1hiuMK",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ClickNEat.Core.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
