// <auto-generated />
using System;
using ClickNEat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickNEat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506173005_FixAWImages")]
    partial class FixAWImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickNEat.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            Description = "Boeuf grillé, laitue, tomate, cheddar",
                            ImageUrl = "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger Classic",
                            Price = 12.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burgers",
                            Description = "Boeuf grillé, bacon, oignon caramélisé, sauce BBQ",
                            ImageUrl = "https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger BBQ",
                            Price = 14.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Burgers",
                            Description = "Galette de pois chiches, avocat, tomate, mayo citron",
                            ImageUrl = "https://images.unsplash.com/photo-1525059696034-4967a8e1dca2?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger Végé",
                            Price = 13.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Burgers",
                            Description = "Double boeuf, double cheddar, bacon, sauce maison",
                            ImageUrl = "https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Burger Double",
                            Price = 17.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, basilic frais",
                            ImageUrl = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza Margherita",
                            Price = 13.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, pepperoni",
                            ImageUrl = "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza Pepperoni",
                            Price = 15.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 7,
                            Category = "Pizzas",
                            Description = "Mozzarella, gorgonzola, parmesan, chèvre",
                            ImageUrl = "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza 4 Fromages",
                            Price = 16.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 8,
                            Category = "Pizzas",
                            Description = "Sauce BBQ, poulet grillé, oignon rouge, mozzarella",
                            ImageUrl = "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Pizza BBQ Poulet",
                            Price = 16.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "Salades",
                            Description = "Romaine, croûtons, parmesan, sauce césar",
                            ImageUrl = "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Salade César",
                            Price = 9.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 10,
                            Category = "Salades",
                            Description = "Tomate, concombre, feta, olives, oignon rouge",
                            ImageUrl = "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Salade Grecque",
                            Price = 10.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 11,
                            Category = "Salades",
                            Description = "Poulet grillé, mesclun, avocat, vinaigrette miel-moutarde",
                            ImageUrl = "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Salade Poulet Grillé",
                            Price = 12.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accompagnements",
                            Description = "Frites maison croustillantes",
                            ImageUrl = "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 4.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accompagnements",
                            Description = "Frites, fromage en grains, sauce brune",
                            ImageUrl = "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 8.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accompagnements",
                            Description = "Rondelles d'oignon panées, sauce ranch",
                            ImageUrl = "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Rondelles d'oignon",
                            Price = 6.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accompagnements",
                            Description = "Soupe maison avec pain grillé",
                            ImageUrl = "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Soupe du jour",
                            Price = 5.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 16,
                            Category = "Desserts",
                            Description = "Moelleux au chocolat, coulis de caramel",
                            ImageUrl = "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Gâteau au chocolat",
                            Price = 6.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = "Desserts",
                            Description = "Crème brûlée à la vanille",
                            ImageUrl = "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Crème brûlée",
                            Price = 5.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 18,
                            Category = "Desserts",
                            Description = "Tiramisu classique au café et mascarpone",
                            ImageUrl = "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 6.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 19,
                            Category = "Boissons",
                            Description = "355 ml",
                            ImageUrl = "https://images.unsplash.com/photo-1554866585-cd94860890b7?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 20,
                            Category = "Boissons",
                            Description = "500 ml",
                            ImageUrl = "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Eau",
                            Price = 1.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 21,
                            Category = "Boissons",
                            Description = "Jus d'orange pressé, 300 ml",
                            ImageUrl = "https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Jus d'orange",
                            Price = 3.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 22,
                            Category = "Boissons",
                            Description = "Citron frais, menthe, eau gazeuse",
                            ImageUrl = "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9e?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Limonade maison",
                            Price = 3.99m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 23,
                            Category = "Boissons",
                            Description = "Espresso, allongé ou cappuccino",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 2.49m,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 50,
                            Category = "Burgers",
                            Description = "Deux galettes de boeuf, sauce spéciale, laitue, fromage, cornichons, oignon",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-big-mac-1?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Big Mac",
                            Price = 7.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 51,
                            Category = "Burgers",
                            Description = "Double galette de boeuf, cornichons, oignons, moutarde, ketchup, fromage",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-double-cheeseburger?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "McDouble",
                            Price = 4.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 52,
                            Category = "Burgers",
                            Description = "Poulet croustillant, mayo, laitue",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-mcchicken?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "McChicken",
                            Price = 5.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 53,
                            Category = "Burgers",
                            Description = "Filet de poisson pané, sauce tartare, fromage",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-filet-o-fish-1?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Filet-O-Fish",
                            Price = 6.29m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 54,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes — portion medium",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-fries-medium?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Frites Medium",
                            Price = 3.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 55,
                            Category = "Accompagnements",
                            Description = "Morceaux de poulet croustillants avec sauce au choix",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-10-chicken-mcnuggets-1?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "McNuggets 10 pcs",
                            Price = 8.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 56,
                            Category = "Accompagnements",
                            Description = "Morceaux de poulet croustillants avec sauce au choix",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-6-chicken-mcnuggets?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "McNuggets 6 pcs",
                            Price = 5.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 57,
                            Category = "Desserts",
                            Description = "Crème glacée vanille avec biscuits Oreo écrasés",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-mcflurry-oreo-regular-size?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "McFlurry Oreo",
                            Price = 4.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 58,
                            Category = "Desserts",
                            Description = "Crème glacée vanille nappée de caramel chaud",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-hot-caramel-sundae?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Sundae Caramel",
                            Price = 2.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 59,
                            Category = "Desserts",
                            Description = "Chausson aux pommes dorées et croustillantes",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-baked-apple-pie?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Tarte aux pommes",
                            Price = 1.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 63,
                            Category = "Burgers",
                            Description = "Galette de boeuf 1/4 lb, fromage fondu, oignons, cornichons, moutarde, ketchup",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-quarter-pounder-cheese?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Quarter Pounder",
                            Price = 8.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 64,
                            Category = "Burgers",
                            Description = "Filet de poulet croustillant, laitue croquante, mayo — sandwich signature",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-mccrispy-1?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "McCrispy",
                            Price = 7.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 65,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes, sauce brune, fromage en grains — classique québécois",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-poutine?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 5.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 66,
                            Category = "Accompagnements",
                            Description = "Mélange de laitues fraîches, tomates cerises, vinaigrette au choix",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-side-salad?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Salade latérale",
                            Price = 3.29m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 67,
                            Category = "Accompagnements",
                            Description = "Tranches de pommes fraîches — accompagnement santé",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-apple-slices?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Tranches de pommes",
                            Price = 1.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 68,
                            Category = "Déjeuner",
                            Description = "Oeuf, fromage, jambon canadien sur muffin anglais grillé",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-egg-mcmuffin?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Egg McMuffin",
                            Price = 5.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 69,
                            Category = "Desserts",
                            Description = "Crème glacée à la vanille onctueuse — cornet gaufrette",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-vanilla-cone?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Cornet de crème glacée",
                            Price = 1.29m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 70,
                            Category = "Desserts",
                            Description = "Crème glacée vanille, sauce au chocolat chaud",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-hot-fudge-sundae?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Sundae sauce chaude",
                            Price = 2.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 60,
                            Category = "Boissons",
                            Description = "Grand format — 591 ml",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-coca-cola?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 61,
                            Category = "Boissons",
                            Description = "Café fraîchement torréfié, taille medium",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-premium-roast-coffee-medium-product?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Café McCafé",
                            Price = 1.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 62,
                            Category = "Boissons",
                            Description = "Lait au chocolat froid, 1% — 500 ml",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-chocolate-milk-1?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Lait au chocolat",
                            Price = 1.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 71,
                            Category = "Boissons",
                            Description = "Boisson gazeuse citron-lime — grand format 591 ml",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-sprite?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Sprite",
                            Price = 2.49m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 72,
                            Category = "Boissons",
                            Description = "Eau purifiée en bouteille — 591 ml",
                            ImageUrl = "https://s7d1.scene7.com/is/image/mcdonalds/mcdonalds-dasani-water?wid=500&hei=350&fmt=jpeg",
                            IsAvailable = true,
                            Name = "Eau Dasani",
                            Price = 1.99m,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 100,
                            Category = "Burgers",
                            Description = "Double galette de boeuf grillé, laitue, tomate, fromage cheddar, sauce mayo",
                            ImageUrl = "https://web.aw.ca/static/media/teen-burger-desktop-399_en.0b60336c.jpg",
                            IsAvailable = true,
                            Name = "Teen Burger",
                            Price = 9.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 101,
                            Category = "Burgers",
                            Description = "Galette de boeuf grillé, laitue, tomate, mayonnaise — l'originale A&W",
                            ImageUrl = "https://web.aw.ca/static/media/mama-burger-2023-dt-en.7b905ded.jpg",
                            IsAvailable = true,
                            Name = "Mama Burger",
                            Price = 7.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 102,
                            Category = "Burgers",
                            Description = "Galette de boeuf, fromage mozzarella fondu, sauce tomate, laitue croustillante",
                            ImageUrl = "https://web.aw.ca/static/media/mozza-dt-2023-en.ae0e4fea.jpg",
                            IsAvailable = true,
                            Name = "Mozza Burger",
                            Price = 8.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 103,
                            Category = "Burgers",
                            Description = "Mini burger parfait — galette de boeuf, ketchup, moutarde",
                            ImageUrl = "https://web.aw.ca/static/media/6_buddy_burger-dt-en.0d1643c1.jpg",
                            IsAvailable = true,
                            Name = "Buddy Burger",
                            Price = 4.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 104,
                            Category = "Burgers",
                            Description = "Triple galette de boeuf, triple fromage, bacon — le plus costaud de la famille",
                            ImageUrl = "https://web.aw.ca/static/media/best-burger-ever-burger-desktop-en.c615859d.jpg",
                            IsAvailable = true,
                            Name = "Uncle Burger",
                            Price = 13.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 105,
                            Category = "Burgers",
                            Description = "Champignons sautés, fromage mozzarella fondu, galette de boeuf grillé",
                            ImageUrl = "https://web.aw.ca/static/media/mushroom_mozza_desktop_hero_en.ec099922.jpg",
                            IsAvailable = true,
                            Name = "Champignon Mozza Burger",
                            Price = 10.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 106,
                            Category = "Poulet",
                            Description = "Poulet croustillant épicé Nashville, salade de chou, mayo piquante",
                            ImageUrl = "https://web.aw.ca/static/media/nashville-hot-chicken-sandwich-desktop-en.9d1627e1.jpg",
                            IsAvailable = true,
                            Name = "Nashville Hot Chicken Burger",
                            Price = 10.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 107,
                            Category = "Poulet",
                            Description = "Filet de poulet entier croustillant, salade de chou crémeuse, pain brioché",
                            ImageUrl = "https://web.aw.ca/static/media/nashville-hot-chicken-sandwich-desktop-en.9d1627e1.jpg",
                            IsAvailable = true,
                            Name = "Chubby Chicken",
                            Price = 8.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 108,
                            Category = "Poulet",
                            Description = "6 morceaux de poulet pané croustillant, sauce trempette au choix",
                            ImageUrl = "https://web.aw.ca/static/media/chicken-nuggets-en.ffbf1cd1.jpg",
                            IsAvailable = true,
                            Name = "Chicken Nuggets",
                            Price = 6.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 109,
                            Category = "Accompagnements",
                            Description = "Rondelles d'oignon croustillantes — la signature A&W depuis 1956",
                            ImageUrl = "https://web.aw.ca/static/media/onions_hero.e0bd333a.jpg",
                            IsAvailable = true,
                            Name = "Rondelles d'oignon",
                            Price = 4.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 110,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes au sel de mer — portion medium",
                            ImageUrl = "https://web.aw.ca/static/media/W18-0610_AW_SpicyGuac_LTO_Fries_desktop_hero_2396x1473_EN.f1f58d9a.jpg",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 3.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 111,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes, sauce brune maison, fromage en grains",
                            ImageUrl = "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&h=350&fit=crop&auto=format",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 5.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 112,
                            Category = "Boissons",
                            Description = "Bière de racines A&W, recette originale depuis 1919 — 473 ml",
                            ImageUrl = "https://web.aw.ca/static/media/carousel_rootbeer_1.235d06f8.jpg",
                            IsAvailable = true,
                            Name = "Root Beer A&W",
                            Price = 3.29m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 113,
                            Category = "Boissons",
                            Description = "Root Beer A&W avec une boule généreuse de crème glacée à la vanille",
                            ImageUrl = "https://web.aw.ca/static/media/carousel_rootbeer_1.235d06f8.jpg",
                            IsAvailable = true,
                            Name = "Root Beer Float",
                            Price = 4.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 114,
                            Category = "Boissons",
                            Description = "Limonade fraîche pressée — 473 ml",
                            ImageUrl = "https://web.aw.ca/static/media/AW_HP_EN_1757x1080_Lemonade.c4c8349f.jpg",
                            IsAvailable = true,
                            Name = "Limonade",
                            Price = 3.49m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 115,
                            Category = "Boissons",
                            Description = "Café fraîchement torréfié, taille medium",
                            ImageUrl = "https://web.aw.ca/static/media/coffee-latte-dt-en.ffc07a9d.jpg",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 2.99m,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 116,
                            Category = "Déjeuner",
                            Description = "Oeufs, bacon de boeuf, toast grillé beurré — servi toute la journée",
                            ImageUrl = "https://web.aw.ca/static/media/all-day-breakfast-hero-desktop.a109de6d.jpg",
                            IsAvailable = true,
                            Name = "Déjeuner Complet",
                            Price = 8.99m,
                            RestaurantId = 3
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#FF416C",
                            CoverImageUrl = "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=400&fit=crop&auto=format",
                            Description = "Burgers · Pizzas · Salades · Poutine",
                            LogoUrl = "",
                            Name = "Le Comptoir"
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = "#DA291C",
                            CoverImageUrl = "https://images.unsplash.com/photo-1586816001966-79b736744398?w=800&h=400&fit=crop&auto=format",
                            Description = "Big Mac · McNuggets · McFlurry",
                            LogoUrl = "https://www.mcdonalds.com/content/dam/sites/ca/nfl/icons/McD-squareLogo.png",
                            Name = "McDonald's"
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = "#F5821F",
                            CoverImageUrl = "https://web.aw.ca/static/media/desktop-hero.7d0c8be4.jpg",
                            Description = "Teen Burger · Onion Rings · Root Beer",
                            LogoUrl = "https://web.aw.ca/logo512.png",
                            Name = "A&W"
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@clickneat.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$X8aEcMTN7Ag/5iqJgyr1N.lrQ4D8X67/kevqA6B5qUxo3BDQpbHKy",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "client@clickneat.com",
                            Name = "Client Test",
                            PasswordHash = "$2a$11$uumzhUwh0rpbuNR/XzSrC.i6rWaHiyhSNEgVAcgTMlGpnfF1hiuMK",
                            Role = "Customer"
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ClickNEat.Core.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
