// <auto-generated />
using System;
using ClickNEat.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClickNEat.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521175713_AddTimHortons")]
    partial class AddTimHortons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClickNEat.Core.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            Description = "Boeuf grillé, laitue, tomate, cheddar",
                            ImageUrl = "/images/item-1.jpg",
                            IsAvailable = true,
                            Name = "Burger Classic",
                            Price = 12.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 2,
                            Category = "Burgers",
                            Description = "Boeuf grillé, bacon, oignon caramélisé, sauce BBQ",
                            ImageUrl = "/images/item-2.jpg",
                            IsAvailable = true,
                            Name = "Burger BBQ",
                            Price = 14.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 3,
                            Category = "Burgers",
                            Description = "Galette de pois chiches, avocat, tomate, mayo citron",
                            ImageUrl = "/images/item-3.jpg",
                            IsAvailable = true,
                            Name = "Burger Végé",
                            Price = 13.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 4,
                            Category = "Burgers",
                            Description = "Double boeuf, double cheddar, bacon, sauce maison",
                            ImageUrl = "/images/item-4.jpg",
                            IsAvailable = true,
                            Name = "Burger Double",
                            Price = 17.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 5,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, basilic frais",
                            ImageUrl = "/images/item-5.jpg",
                            IsAvailable = true,
                            Name = "Pizza Margherita",
                            Price = 13.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 6,
                            Category = "Pizzas",
                            Description = "Sauce tomate, mozzarella, pepperoni",
                            ImageUrl = "/images/item-6.jpg",
                            IsAvailable = true,
                            Name = "Pizza Pepperoni",
                            Price = 15.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 7,
                            Category = "Pizzas",
                            Description = "Mozzarella, gorgonzola, parmesan, chèvre",
                            ImageUrl = "/images/item-7.jpg",
                            IsAvailable = true,
                            Name = "Pizza 4 Fromages",
                            Price = 16.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 8,
                            Category = "Pizzas",
                            Description = "Sauce BBQ, poulet grillé, oignon rouge, mozzarella",
                            ImageUrl = "/images/item-8.jpg",
                            IsAvailable = true,
                            Name = "Pizza BBQ Poulet",
                            Price = 16.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 9,
                            Category = "Salades",
                            Description = "Romaine, croûtons, parmesan, sauce césar",
                            ImageUrl = "/images/item-9.jpg",
                            IsAvailable = true,
                            Name = "Salade César",
                            Price = 9.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 10,
                            Category = "Salades",
                            Description = "Tomate, concombre, feta, olives, oignon rouge",
                            ImageUrl = "/images/item-10.jpg",
                            IsAvailable = true,
                            Name = "Salade Grecque",
                            Price = 10.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 11,
                            Category = "Salades",
                            Description = "Poulet grillé, mesclun, avocat, vinaigrette miel-moutarde",
                            ImageUrl = "/images/item-11.jpg",
                            IsAvailable = true,
                            Name = "Salade Poulet Grillé",
                            Price = 12.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accompagnements",
                            Description = "Frites maison croustillantes",
                            ImageUrl = "/images/item-12.jpg",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 4.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 13,
                            Category = "Accompagnements",
                            Description = "Frites, fromage en grains, sauce brune",
                            ImageUrl = "/images/item-13.jpg",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 8.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accompagnements",
                            Description = "Rondelles d'oignon panées, sauce ranch",
                            ImageUrl = "/images/item-14.jpg",
                            IsAvailable = true,
                            Name = "Rondelles d'oignon",
                            Price = 6.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 15,
                            Category = "Accompagnements",
                            Description = "Soupe maison avec pain grillé",
                            ImageUrl = "/images/item-15.jpg",
                            IsAvailable = true,
                            Name = "Soupe du jour",
                            Price = 5.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 16,
                            Category = "Desserts",
                            Description = "Moelleux au chocolat, coulis de caramel",
                            ImageUrl = "/images/item-16.jpg",
                            IsAvailable = true,
                            Name = "Gâteau au chocolat",
                            Price = 6.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 17,
                            Category = "Desserts",
                            Description = "Crème brûlée à la vanille",
                            ImageUrl = "/images/item-17.jpg",
                            IsAvailable = true,
                            Name = "Crème brûlée",
                            Price = 5.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 18,
                            Category = "Desserts",
                            Description = "Tiramisu classique au café et mascarpone",
                            ImageUrl = "/images/item-18.jpg",
                            IsAvailable = true,
                            Name = "Tiramisu",
                            Price = 6.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 19,
                            Category = "Boissons",
                            Description = "355 ml",
                            ImageUrl = "/images/item-19.jpg",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 20,
                            Category = "Boissons",
                            Description = "500 ml",
                            ImageUrl = "/images/item-20.jpg",
                            IsAvailable = true,
                            Name = "Eau",
                            Price = 1.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 21,
                            Category = "Boissons",
                            Description = "Jus d'orange pressé, 300 ml",
                            ImageUrl = "/images/item-21.jpg",
                            IsAvailable = true,
                            Name = "Jus d'orange",
                            Price = 3.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 22,
                            Category = "Boissons",
                            Description = "Citron frais, menthe, eau gazeuse",
                            ImageUrl = "/images/item-22.jpg",
                            IsAvailable = true,
                            Name = "Limonade maison",
                            Price = 3.99m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 23,
                            Category = "Boissons",
                            Description = "Espresso, allongé ou cappuccino",
                            ImageUrl = "/images/item-23.jpg",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 2.49m,
                            RestaurantId = 1,
                            Tags = ""
                        },
                        new
                        {
                            Id = 50,
                            Category = "Burgers",
                            Description = "Deux galettes de boeuf, sauce spéciale, laitue, fromage, cornichons, oignon",
                            ImageUrl = "/images/item-50.jpg",
                            IsAvailable = true,
                            Name = "Big Mac",
                            Price = 7.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 51,
                            Category = "Burgers",
                            Description = "Double galette de boeuf, cornichons, oignons, moutarde, ketchup, fromage",
                            ImageUrl = "/images/item-51.jpg",
                            IsAvailable = true,
                            Name = "McDouble",
                            Price = 4.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 52,
                            Category = "Burgers",
                            Description = "Poulet croustillant, mayo, laitue",
                            ImageUrl = "/images/item-52.jpg",
                            IsAvailable = true,
                            Name = "McChicken",
                            Price = 5.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 53,
                            Category = "Burgers",
                            Description = "Filet de poisson pané, sauce tartare, fromage",
                            ImageUrl = "/images/item-53.jpg",
                            IsAvailable = true,
                            Name = "Filet-O-Fish",
                            Price = 6.29m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 63,
                            Category = "Burgers",
                            Description = "Galette de boeuf 1/4 lb, fromage fondu, oignons, cornichons, moutarde, ketchup",
                            ImageUrl = "/images/item-63.jpg",
                            IsAvailable = true,
                            Name = "Quarter Pounder",
                            Price = 8.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 64,
                            Category = "Burgers",
                            Description = "Filet de poulet croustillant, laitue croquante, mayo — sandwich signature",
                            ImageUrl = "/images/item-64.jpg",
                            IsAvailable = true,
                            Name = "McCrispy",
                            Price = 7.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 54,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes — portion medium",
                            ImageUrl = "/images/item-54.jpg",
                            IsAvailable = true,
                            Name = "Frites Medium",
                            Price = 3.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 55,
                            Category = "Accompagnements",
                            Description = "Morceaux de poulet croustillants avec sauce au choix",
                            ImageUrl = "/images/item-55.jpg",
                            IsAvailable = true,
                            Name = "McNuggets 10 pcs",
                            Price = 8.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 56,
                            Category = "Accompagnements",
                            Description = "Morceaux de poulet croustillants avec sauce au choix",
                            ImageUrl = "/images/item-56.jpg",
                            IsAvailable = true,
                            Name = "McNuggets 6 pcs",
                            Price = 5.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 65,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes, sauce brune, fromage en grains — classique québécois",
                            ImageUrl = "/images/item-13.jpg",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 5.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 66,
                            Category = "Accompagnements",
                            Description = "Mélange de laitues fraîches, tomates cerises, vinaigrette au choix",
                            ImageUrl = "/images/item-66.jpg",
                            IsAvailable = true,
                            Name = "Salade latérale",
                            Price = 3.29m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 67,
                            Category = "Accompagnements",
                            Description = "Tranches de pommes fraîches — accompagnement santé",
                            ImageUrl = "/images/item-67.jpg",
                            IsAvailable = true,
                            Name = "Tranches de pommes",
                            Price = 1.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 57,
                            Category = "Desserts",
                            Description = "Crème glacée vanille avec biscuits Oreo écrasés",
                            ImageUrl = "/images/item-57.jpg",
                            IsAvailable = true,
                            Name = "McFlurry Oreo",
                            Price = 4.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 58,
                            Category = "Desserts",
                            Description = "Crème glacée vanille nappée de caramel chaud",
                            ImageUrl = "/images/item-58.jpg",
                            IsAvailable = true,
                            Name = "Sundae Caramel",
                            Price = 2.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 59,
                            Category = "Desserts",
                            Description = "Chausson aux pommes dorées et croustillantes",
                            ImageUrl = "/images/item-59.jpg",
                            IsAvailable = true,
                            Name = "Tarte aux pommes",
                            Price = 1.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 69,
                            Category = "Desserts",
                            Description = "Crème glacée à la vanille onctueuse — cornet gaufrette",
                            ImageUrl = "/images/item-69.jpg",
                            IsAvailable = true,
                            Name = "Cornet de crème glacée",
                            Price = 1.29m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 70,
                            Category = "Desserts",
                            Description = "Crème glacée vanille, sauce au chocolat chaud",
                            ImageUrl = "/images/item-70.jpg",
                            IsAvailable = true,
                            Name = "Sundae sauce chaude",
                            Price = 2.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 68,
                            Category = "Déjeuner",
                            Description = "Oeuf, fromage, jambon canadien sur muffin anglais grillé",
                            ImageUrl = "/images/item-68.jpg",
                            IsAvailable = true,
                            Name = "Egg McMuffin",
                            Price = 5.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 60,
                            Category = "Boissons",
                            Description = "Grand format — 591 ml",
                            ImageUrl = "/images/item-60.jpg",
                            IsAvailable = true,
                            Name = "Coca-Cola",
                            Price = 2.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 61,
                            Category = "Boissons",
                            Description = "Café fraîchement torréfié, taille medium",
                            ImageUrl = "/images/item-61.jpg",
                            IsAvailable = true,
                            Name = "Café McCafé",
                            Price = 1.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 62,
                            Category = "Boissons",
                            Description = "Lait au chocolat froid, 1% — 500 ml",
                            ImageUrl = "/images/item-62.jpg",
                            IsAvailable = true,
                            Name = "Lait au chocolat",
                            Price = 1.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 71,
                            Category = "Boissons",
                            Description = "Boisson gazeuse citron-lime — grand format 591 ml",
                            ImageUrl = "/images/item-71.jpg",
                            IsAvailable = true,
                            Name = "Sprite",
                            Price = 2.49m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 72,
                            Category = "Boissons",
                            Description = "Eau purifiée en bouteille — 591 ml",
                            ImageUrl = "/images/item-72.jpg",
                            IsAvailable = true,
                            Name = "Eau Dasani",
                            Price = 1.99m,
                            RestaurantId = 2,
                            Tags = ""
                        },
                        new
                        {
                            Id = 100,
                            Category = "Burgers",
                            Description = "Double galette de boeuf grillé, laitue, tomate, fromage cheddar, sauce mayo",
                            ImageUrl = "/images/item-100.jpg",
                            IsAvailable = true,
                            Name = "Teen Burger",
                            Price = 9.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 101,
                            Category = "Burgers",
                            Description = "Galette de boeuf grillé, laitue, tomate, mayonnaise — l'originale A&W",
                            ImageUrl = "/images/item-101.jpg",
                            IsAvailable = true,
                            Name = "Mama Burger",
                            Price = 7.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 102,
                            Category = "Burgers",
                            Description = "Galette de boeuf, fromage mozzarella fondu, sauce tomate, laitue croustillante",
                            ImageUrl = "/images/item-102.jpg",
                            IsAvailable = true,
                            Name = "Mozza Burger",
                            Price = 8.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 103,
                            Category = "Burgers",
                            Description = "Mini burger parfait — galette de boeuf, ketchup, moutarde",
                            ImageUrl = "/images/item-103.jpg",
                            IsAvailable = true,
                            Name = "Buddy Burger",
                            Price = 4.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 104,
                            Category = "Burgers",
                            Description = "Triple galette de boeuf, triple fromage, bacon — le plus costaud de la famille",
                            ImageUrl = "/images/item-104.jpg",
                            IsAvailable = true,
                            Name = "Uncle Burger",
                            Price = 13.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 105,
                            Category = "Burgers",
                            Description = "Champignons sautés, fromage mozzarella fondu, galette de boeuf grillé",
                            ImageUrl = "/images/item-105.jpg",
                            IsAvailable = true,
                            Name = "Champignon Mozza Burger",
                            Price = 10.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 106,
                            Category = "Poulet",
                            Description = "Poulet croustillant épicé Nashville, salade de chou, mayo piquante",
                            ImageUrl = "/images/item-106.jpg",
                            IsAvailable = true,
                            Name = "Nashville Hot Chicken Burger",
                            Price = 10.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 107,
                            Category = "Poulet",
                            Description = "Filet de poulet entier croustillant, salade de chou crémeuse, pain brioché",
                            ImageUrl = "/images/item-106.jpg",
                            IsAvailable = true,
                            Name = "Chubby Chicken",
                            Price = 8.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 108,
                            Category = "Poulet",
                            Description = "6 morceaux de poulet pané croustillant, sauce trempette au choix",
                            ImageUrl = "/images/item-108.jpg",
                            IsAvailable = true,
                            Name = "Chicken Nuggets",
                            Price = 6.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 109,
                            Category = "Accompagnements",
                            Description = "Rondelles d'oignon croustillantes — la signature A&W depuis 1956",
                            ImageUrl = "/images/item-109.jpg",
                            IsAvailable = true,
                            Name = "Rondelles d'oignon",
                            Price = 4.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 110,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes au sel de mer — portion medium",
                            ImageUrl = "/images/item-110.jpg",
                            IsAvailable = true,
                            Name = "Frites",
                            Price = 3.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 111,
                            Category = "Accompagnements",
                            Description = "Frites croustillantes, sauce brune maison, fromage en grains",
                            ImageUrl = "/images/item-13.jpg",
                            IsAvailable = true,
                            Name = "Poutine",
                            Price = 5.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 112,
                            Category = "Boissons",
                            Description = "Bière de racines A&W, recette originale depuis 1919 — 473 ml",
                            ImageUrl = "/images/item-112.jpg",
                            IsAvailable = true,
                            Name = "Root Beer A&W",
                            Price = 3.29m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 113,
                            Category = "Boissons",
                            Description = "Root Beer A&W avec une boule généreuse de crème glacée à la vanille",
                            ImageUrl = "/images/item-112.jpg",
                            IsAvailable = true,
                            Name = "Root Beer Float",
                            Price = 4.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 114,
                            Category = "Boissons",
                            Description = "Limonade fraîche pressée — 473 ml",
                            ImageUrl = "/images/item-114.jpg",
                            IsAvailable = true,
                            Name = "Limonade",
                            Price = 3.49m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 115,
                            Category = "Boissons",
                            Description = "Café fraîchement torréfié, taille medium",
                            ImageUrl = "/images/item-115.jpg",
                            IsAvailable = true,
                            Name = "Café",
                            Price = 2.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 116,
                            Category = "Déjeuner",
                            Description = "Oeufs, bacon de boeuf, toast grillé beurré — servi toute la journée",
                            ImageUrl = "/images/item-116.jpg",
                            IsAvailable = true,
                            Name = "Déjeuner Complet",
                            Price = 8.99m,
                            RestaurantId = 3,
                            Tags = ""
                        },
                        new
                        {
                            Id = 200,
                            Category = "Boissons",
                            Description = "Café brassé à la canadienne, léger et équilibré",
                            ImageUrl = "/images/item-200.png",
                            IsAvailable = true,
                            Name = "Café Original",
                            Price = 2.19m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 201,
                            Category = "Boissons",
                            Description = "Café original avec double crème et double sucre — l'emblème canadien",
                            ImageUrl = "/images/item-201.png",
                            IsAvailable = true,
                            Name = "Double Double",
                            Price = 2.49m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 202,
                            Category = "Boissons",
                            Description = "Cappuccino glacé crémeux, la recette originale Tim Hortons",
                            ImageUrl = "/images/item-202.png",
                            IsAvailable = true,
                            Name = "Ice Capp",
                            Price = 4.29m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 203,
                            Category = "Boissons",
                            Description = "Café doux à la vanille française, chaud et velouté",
                            ImageUrl = "/images/item-203.png",
                            IsAvailable = true,
                            Name = "French Vanilla",
                            Price = 3.29m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 204,
                            Category = "Déjeuner",
                            Description = "Wrap grillé garni de bacon croustillant, oeuf et fromage cheddar",
                            ImageUrl = "/images/item-204.png",
                            IsAvailable = true,
                            Name = "Wrap Bacon Oeuf Fromage",
                            Price = 5.99m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 205,
                            Category = "Déjeuner",
                            Description = "Saucisse, oeuf brouillé, fromage et sauce maison dans un wrap chaud",
                            ImageUrl = "/images/item-205.png",
                            IsAvailable = true,
                            Name = "Farmers Wrap",
                            Price = 6.49m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 206,
                            Category = "Déjeuner",
                            Description = "Galette de pommes de terre dorée et croustillante",
                            ImageUrl = "/images/item-206.png",
                            IsAvailable = true,
                            Name = "Hashbrown",
                            Price = 1.99m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 207,
                            Category = "Boulangerie",
                            Description = "Boules de pâte glacées, les originaux Tim Hortons (10 pcs)",
                            ImageUrl = "/images/item-207.png",
                            IsAvailable = true,
                            Name = "Timbits Glacés",
                            Price = 3.49m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 208,
                            Category = "Boulangerie",
                            Description = "Boules de pâte au chocolat glacé (10 pcs)",
                            ImageUrl = "/images/item-208.png",
                            IsAvailable = true,
                            Name = "Timbits Chocolat",
                            Price = 3.49m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 209,
                            Category = "Boulangerie",
                            Description = "Beigne fourré à la crème pâtissière, glacé au chocolat",
                            ImageUrl = "/images/item-209.png",
                            IsAvailable = true,
                            Name = "Beigne Boston Cream",
                            Price = 1.89m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 210,
                            Category = "Boulangerie",
                            Description = "Beigne glacé au sirop d'érable — classique québécois",
                            ImageUrl = "/images/item-210.png",
                            IsAvailable = true,
                            Name = "Beigne à l'érable",
                            Price = 1.89m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 211,
                            Category = "Boulangerie",
                            Description = "Muffin moelleux aux bleuets sauvages, cuit le matin",
                            ImageUrl = "/images/item-211.png",
                            IsAvailable = true,
                            Name = "Muffin aux bleuets",
                            Price = 2.29m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 212,
                            Category = "Boulangerie",
                            Description = "Croissant feuilleté au beurre, légèrement doré",
                            ImageUrl = "/images/item-212.png",
                            IsAvailable = true,
                            Name = "Croissant au beurre",
                            Price = 2.49m,
                            RestaurantId = 4,
                            Tags = ""
                        },
                        new
                        {
                            Id = 213,
                            Category = "Boulangerie",
                            Description = "Carré au chocolat fondant, riche et décadent",
                            ImageUrl = "/images/item-213.png",
                            IsAvailable = true,
                            Name = "Brownie au chocolat",
                            Price = 2.49m,
                            RestaurantId = 4,
                            Tags = ""
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PaidWithPoints")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccentColor = "#FF416C",
                            CoverImageUrl = "/images/restaurant-1-cover.jpg",
                            Description = "Burgers · Pizzas · Salades · Poutine",
                            LogoUrl = "",
                            Name = "Le Comptoir"
                        },
                        new
                        {
                            Id = 2,
                            AccentColor = "#DA291C",
                            CoverImageUrl = "/images/restaurant-2-cover.jpg",
                            Description = "Big Mac · McNuggets · McFlurry",
                            LogoUrl = "/images/restaurant-2-logo.png",
                            Name = "McDonald's"
                        },
                        new
                        {
                            Id = 3,
                            AccentColor = "#F5821F",
                            CoverImageUrl = "/images/restaurant-3-cover.jpg",
                            Description = "Teen Burger · Onion Rings · Root Beer",
                            LogoUrl = "/images/restaurant-3-logo.png",
                            Name = "A&W"
                        },
                        new
                        {
                            Id = 4,
                            AccentColor = "#C8102E",
                            CoverImageUrl = "/images/restaurant-4-cover.jpg",
                            Description = "Double Double · Timbits · Beignes · Muffins",
                            LogoUrl = "/images/restaurant-4-logo.png",
                            Name = "Tim Hortons"
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPointsEarned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@clickneat.com",
                            IsActive = true,
                            Name = "Admin",
                            PasswordHash = "$2a$11$X8aEcMTN7Ag/5iqJgyr1N.lrQ4D8X67/kevqA6B5qUxo3BDQpbHKy",
                            Points = 0,
                            Role = "Admin",
                            TotalPointsEarned = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "client@clickneat.com",
                            IsActive = true,
                            Name = "Client Test",
                            PasswordHash = "$2a$11$uumzhUwh0rpbuNR/XzSrC.i6rWaHiyhSNEgVAcgTMlGpnfF1hiuMK",
                            Points = 0,
                            Role = "Customer",
                            TotalPointsEarned = 0
                        });
                });

            modelBuilder.Entity("ClickNEat.Core.Models.OrderItem", b =>
                {
                    b.HasOne("ClickNEat.Core.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("ClickNEat.Core.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
